name: Quality Checks
on: [push]
jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip3 install .[dev]
      - name: Check for unused imports
        run: pycln --check .
      - name: Check ordering of imports
        run: isort --check .
      - name: Check code formatting
        run: black --check .
      - name: Check code style
        run: flake8 .
